# Generated by Django 3.1 on 2022-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220918_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
